Repository ammar-nasser/paint-for-kids, pull requests merged in 2021-06, with the labels that each got.

#26 some organization in almost all classes
  Actions/AddCircleAction.cpp
  Actions/AddLineAction.cpp
  Actions/AddRectAction.cpp
  Actions/AddTriAction.cpp
  Actions/AddTriAction.h
  Actions/ChangeColorActions/ChngBkgndClr.cpp
  Actions/ChangeColorActions/ChngBkgndClr.h
  Actions/ChangeColorActions/ChngDrawClr.cpp
  Actions/ChangeColorActions/ChngDrawClr.h
  Actions/ChangeColorActions/ChngFillClr.cpp
  Actions/ChangeColorActions/ChngFillClr.h
  Actions/Copy.cpp
  Actions/Copy.h
  Actions/Delete.cpp
  Actions/Delete.h
  Actions/GameAction.cpp
  Actions/GameAction.h
  Actions/GameArea.cpp
  Actions/GameColorOnly.cpp
  Actions/GameColorOnly.h
  Actions/GameColorShape.cpp
  Actions/GameShapeOnly.h
  Actions/Move.cpp
  Actions/Move.h
  Actions/Paste.cpp
  Actions/Paste.h
  Actions/Select.cpp
  Actions/Select.h
  Actions/ToPlay.cpp
  Actions/ToPlay.h
  ApplicationManager.cpp
  ApplicationManager.h
  CMUgraphicsLib/CMUgraphics.cpp
  Figures/CCircle.cpp
  Figures/CCircle.h
  Figures/CFigure.cpp
  Figures/CFigure.h
  Figures/CLine.cpp
  Figures/CLine.h
  Figures/CRectangle.cpp
  Figures/CRectangle.h
  Figures/CTriangle.cpp
  Figures/CTriangle.h
  GUI/ColorWin.cpp
  GUI/ColorWin.h
  GUI/MenuItem.cpp
  GUI/MenuItem.h
  GUI/Output.cpp
  GUI/Output.h
  GUI/ToolBar.cpp
  GUI/ToolBar.h
  GUI/UI_Info.h
  PT-Project.vcxproj
  PT-Project.vcxproj.filters
  Resource.rc
  main_win.ico
  main_win1.ico
  resource.h
Labels: documentation, enhancement

#28 Feature highlight items
  Actions/AddCIrcleAction.h
  Actions/AddCircleAction.cpp
  Actions/AddLineAction.cpp
  Actions/AddLineAction.h
  Actions/AddRectAction.cpp
  Actions/AddRectAction.h
  Actions/AddTriAction.cpp
  Actions/AddTriAction.h
  Actions/ChangeColorActions/ChngBkgndClr.cpp
  Actions/ChangeColorActions/ChngBkgndClr.h
  Actions/ChangeColorActions/ChngDrawClr.cpp
  Actions/ChangeColorActions/ChngDrawClr.h
  Actions/ChangeColorActions/ChngFillClr.cpp
  Actions/ChangeColorActions/ChngFillClr.h
  Actions/Delete.cpp
  Actions/GameAction.h
  Actions/GameArea.cpp
  Actions/GameArea.h
  Actions/GameColorOnly.cpp
  Actions/GameColorOnly.h
  Actions/GameColorShape.cpp
  Actions/GameColorShape.h
  Actions/GameShapeOnly.cpp
  Actions/GameShapeOnly.h
  Actions/Move.cpp
  Actions/Paste.cpp
  Actions/Select.cpp
  Actions/ToPlay.cpp
  ApplicationManager.cpp
  Figures/CCircle.cpp
  Figures/CRectangle.cpp
  Figures/CTriangle.cpp
  GUI/Output.cpp
  GUI/Output.h
  GUI/ToolBar.cpp
  GUI/ToolBar.h
  images/MenuItems/P/H/6.jpg
  images/MenuItems/P/N/6.jpg
Labels: enhancement

#29 Documentation
  Actions/GameAction.cpp
  Actions/GameAction.h
  Actions/Move.cpp
  Actions/Select.cpp
  Actions/Select.h
  Actions/ToPlay.cpp
Labels: documentation

#30 Documentation
  Actions/AddCircleAction.cpp
  Actions/AddLineAction.cpp
  Actions/AddRectAction.cpp
  Actions/AddTriAction.cpp
  Actions/Load.cpp
  Actions/Load.h
  Actions/Resize.cpp
  Actions/Resize.h
  Actions/Save.cpp
  Actions/Save.h
  ApplicationManager.cpp
  ApplicationManager.h
  Figures/CCircle.cpp
  Figures/CCircle.h
  Figures/CFigure.h
  Figures/CLine.cpp
  Figures/CLine.h
  Figures/CRectangle.cpp
  Figures/CRectangle.h
  Figures/CTriangle.cpp
  Figures/CTriangle.h
  GUI/Input.cpp
  GUI/Input.h
  GUI/Output.cpp
  GUI/Output.h
  main.cpp
Labels: documentation
